server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/factory
    username: root
    password: Qzy@13702560366
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.factory.backend.entity
